##Build the docker image
##Push the docker image to docker hub
##SSH into our VM and start the new image

name: Deploy backend
on:
  push:
    branches: [main]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/setup-buildx-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: 100xdevs/todo-app-backend:${{ github.sha }}
      # - name: Deploy to the VM
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
      #     chmod 700 /home/runner/ssh_key
      #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@64.227.169.180 -t "docker stop user_backend 
      #     && docker run --name user_backend -d -p 8080:8080 100xdevs/todo-app-backend:${{ github.sha }}"
